const nouns = {
    singular: [
        "The friend",
        "The lie",
        "The actor",
        "The advertisement",
        "The afternoon",
        "The airport",
        "The ambulance",
        "The animal",
        "The answer",
        "The apple",
        "The army",
        "The balloon",
        "The banana",
        "The battery",
        "The beach",
        "The beard",
        "The bed",
        "The boy",
        "The branch",
        "The breakfast",
        "The brother",
        "Bucharest",
        "The calendar",
        "Cambridge",
        "The camera",
        "The candle",
        "The car",
        "The caravan",
        "The carpet",
        "The cartoon",
        "The church",
        "The compassion",
        "The crayon",
        "The crowd",
        "The daughter",
        "The death",
        "The diamond",
        "The dinner",
        "The disease",
        "The doctor",
        "The dog",
        "The dream",
        "The dress",
        "The easter",
        "The egg",
        "The eggplant",
        "The elephant",
        "The energy",
        "The engine",
        "The evening",
        "The eye",
        "The family",
        "The fish",
        "The flag",
        "The flower",
        "The football",
        "The forest",
        "The fountain",
        "France",
        "The furniture",
        "The garage",
        "The garden",
        "The gas",
        "Gavin",
        "The ghost",
        "The girl",
        "The glass",
        "The gold",
        "The grass",
        "The guitar",
        "The hair",
        "The hamburger",
        "The helicopter",
        "The helmet",
        "The holiday",
        "The honey",
        "The horse",
        "The hospital",
        "The house",
        "The hydrogen",
        "The ice",
        "The insect",
        "The insurance",
        "The iron",
        "The island",
        "The jackal",
        "The jelly",
        "The jewellery",
        "Joy",
        "The juice",
        "The kangaroo",
        "The king",
        "The kitchen",
        "The kite",
        "The knife",
        "The lamp",
        "The lawyer",
        "The leather",
        "Liberty",
        "The library",
        "The lighter",
        "The lion",
        "The lizard",
        "The lock",
        "London",
        "The lunch",
        "The machine",
        "The magazine",
        "The magician",
        "Manchester",
        "The market",
        "The match",
        "The meerkat",
        "The meme",
        "The microphone",
        "The monkey",
        "The morning",
        "The motorcycle",
        "The nail",
        "The napkin",
        "The needle",
        "The nest",
        "The night",
        "The notebook",
        "Oblivion",
        "The ocean",
        "The oil",
        "The orange",
        "The oxygen",
        "The oyster",
        "The painting",
        "The parrot",
        "The pattern",
        "The pencil",
        "The piano",
        "The pillow",
        "The pizza",
        "The planet",
        "The plastic",
        "The potato",
        "The queen",
        "The quill",
        "The rain",
        "The rainbow",
        "The raincoat",
        "The refrigerator",
        "The restaurant",
        "The river",
        "The rocket",
        "The room",
        "The rose",
        "The salvation",
        "The sandwich",
        "The school",
        "The scooter",
        "The shampoo",
        "The sheep",
        "The shoe",
        "The smile",
        "The soccer",
        "The spoon",
        "The stone",
        "The struggle",
        "The sugar",
        "The sweden",
        "The teacher",
        "The telephone",
        "The television",
        "The tennis",
        "The tent",
        "The card",
        "The flag",
        "The fox",
        "The hole",
        "The keyboard",
        "The mountain",
        "The policy",
        "The rocket",
        "The ship",
        "The washing machine",
        "Time",
        "The tomato",
        "The toothbrush",
        "The traffic",
        "The train",
        "The truck",
        "The umbrella",
        "The van",
        "The vase",
        "The vegetable",
        "The vulture",
        "The wall",
        "The water",
        "The whale",
        "The window",
        "The wire",
        "The xylophone",
        "The yacht",
        "The yak",
        "The zebra",
        "The zoo",
    ],
    plural: [
        "Actors",
        "Advertisements",
        "Afternoons",
        "Airports",
        "Ambulances",
        "Animals",
        "Answers",
        "Apples",
        "Armiess",
        "Balloons",
        "Bananas",
        "Batteries",
        "Beachs",
        "Beards",
        "Beds",
        "Boys",
        "Branches",
        "Breakfasts",
        "Brothers",
        "Calendars",
        "Cameras",
        "Candles",
        "Caravans",
        "Carpets",
        "Cars",
        "Cartoons",
        "Churches",
        "Crayons",
        "Crowds",
        "Daughters",
        "Deaths",
        "Diamonds",
        "Dinners",
        "Diseases",
        "Doctors",
        "Dogs",
        "Dreams",
        "Dresses",
        "Eggplants",
        "Eggs",
        "Elephants",
        "Energies",
        "Engines",
        "Evenings",
        "Eyes",
        "Families",
        "Fishes",
        "Flags",
        "Flags",
        "Flowers",
        "Footballs",
        "Forests",
        "Fountains",
        "Foxes",
        "Friends",
        "Furnitures",
        "Garages",
        "Gardens",
        "Gases",
        "Ghosts",
        "Girls",
        "Glasses",
        "Grasses",
        "Guitars",
        "Hairs",
        "Hamburgers",
        "Helicopters",
        "Helmets",
        "Holes",
        "Holidays",
        "Horses",
        "Hospitals",
        "Houses",
        "Icecubes",
        "Insects",
        "Irons",
        "Islands",
        "Jackals",
        "Jellies",
        "Joys",
        "Juices",
        "Kangaroos",
        "Keyboards",
        "Kings",
        "Kitchens",
        "Kites",
        "Knifes",
        "Lamps",
        "Lawyers",
        "Libraries",
        "Lies",
        "Lighters",
        "Lions",
        "Lizards",
        "Locks",
        "Lunches",
        "Machines",
        "Magazines",
        "Magicians",
        "Markets",
        "Matchs",
        "Meerkats",
        "Memes",
        "Microphones",
        "Monkeys",
        "Mornings",
        "Motorcycles",
        "Mountains",
        "Nails",
        "Napkins",
        "Needles",
        "Nests",
        "Nights",
        "Notebooks",
        "Oceans",
        "Oils",
        "Oranges",
        "Oysters",
        "Paintings",
        "Parrots",
        "Patterns",
        "Pencils",
        "Pianos",
        "Pillows",
        "Pizzas",
        "Planets",
        "Plastics",
        "Policies",
        "Potatoes",
        "Queens",
        "Quills",
        "Rainbows",
        "Raincoats",
        "Rains",
        "Refrigerators",
        "Restaurants",
        "Rivers",
        "Rockets",
        "Rooms",
        "Roses",
        "Sandwiches",
        "Schools",
        "Scooters",
        "Shampoos",
        "Sheep",
        "Shoes",
        "Smiles",
        "Spoons",
        "Stones",
        "Struggles",
        "Sugars",
        "Teachers",
        "Telephones",
        "Televisions",
        "Tents",
        "The cards",
        "The rockets",
        "The ships",
        "The waters",
        "Tomatoes",
        "Toothbrushes",
        "Traffics",
        "Trains",
        "Trucks",
        "Umbrellas",
        "Values",
        "Vans",
        "Vases",
        "Vegetables",
        "Vultures",
        "Walls",
        "Washing machines",
        "Whales",
        "Windows",
        "Wires",
        "Xylophones",
        "Yachts",
        "Yaks",
        "Zebras",
        "Zoos",
    ]
};

const verbs = {
    singular: [
        "dies",
        "shakes",
        "grows",
        "speaks",
        "betrays",
        "performs",
        "swallows",
        "clicks",
        "launches",
        "descends",
        "forgives",
        "liberates",
        "severs",
        "acts",
        "breaks",
        "colors",
        "cries",
        "drinks",
        "exits",
        "laughs",
        "plans",
        "runs",
        "shouts",
        "sneezes",
        "touches",
        "writes",
        "answers",
        "builds",
        "coughs",
        "dances",
        "eats",
        "imitates",
        "lies",
        "plays",
        "screams",
        "sings",
        "solves",
        "turns",
        "whistles",
        "approves",
        "buys",
        "creates",
        "describes",
        "edits",
        "invents",
        "listens",
        "reads",
        "sees",
        "skips",
        "studiess",
        "walks",
        "yanks",
        "arranges",
        "coachs",
        "completes",
        "draws",
        "enters",
        "jumps",
        "paints",
        "replaces",
        "shops",
        "sleeps",
        "teachs",
        "wins",
        "zips",
        "concerns",
        "doubts",
        "hates",
        "impresses",
        "likes",
        "minds",
        "perceives",
        "remembers",
        "surprises",
        "promises",
        "decides",
        "feels",
        "hears",
        "knows",
        "looks",
        "notices",
        "realizes",
        "sees",
        "pleases",
        "thinks",
        "dislikes",
        "forgets",
        "hopes",
        "learns",
        "loves",
        "owns",
        "recognizes",
        "smells",
        "prefers",
        "understands",
    ],
    plural: [
        "die",
        "shake",
        "grow",
        "speak",
        "betray",
        "perform",
        "swallow",
        "click",
        "launch",
        "descend",
        "forgive",
        "liberate",
        "sever",
        "act",
        "break",
        "color",
        "cry",
        "drink",
        "exit",
        "laugh",
        "plan",
        "run",
        "shout",
        "sneeze",
        "touch",
        "write",
        "answer",
        "build",
        "cough",
        "dance",
        "eat",
        "imitate",
        "lie",
        "play",
        "scream",
        "sing",
        "solve",
        "turn",
        "whistle",
        "approve",
        "buy",
        "create",
        "describe",
        "edit",
        "invent",
        "listen",
        "read",
        "see",
        "skip",
        "study",
        "walk",
        "yank",
        "arrange",
        "coach",
        "complete",
        "draw",
        "enter",
        "jump",
        "paint",
        "replace",
        "shop",
        "sleep",
        "teach",
        "win",
        "zip",
        "concern",
        "doubt",
        "hate",
        "impress",
        "like",
        "mind",
        "perceive",
        "remember",
        "surprise",
        "promise",
        "decide",
        "feel",
        "hear",
        "know",
        "look",
        "notice",
        "realize",
        "see",
        "please",
        "think",
        "dislike",
        "forget",
        "hope",
        "learn",
        "love",
        "own",
        "recognize",
        "smell",
        "prefer",
        "understand",
    ]
};

function shuffle(arr) {
    return arr.sort(() => Math.random() > 0.5 ? 1 : -1);
}

function getNounVerb() {
    const number = Math.random() > 0.5 ? "singular" : "plural";
    let random_noun = shuffle(nouns[number])[0];
    let random_verb = shuffle(verbs[number])[0];
    return `${random_noun} ${random_verb}`;
}

document.getElementById("nouns-verbs-button").onclick = function(e) {
    e.preventDefault();

    let target = document.getElementById("nouns-verbs-target");
    target.innerHTML = '';
    let noun_verb_node = document.createElement('p');
    noun_verb_node.innerHTML = getNounVerb();
    target.appendChild(noun_verb_node)
}

